name: Test for action

on:
    push:
        tags:
            - "V*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Checkout
            - name: Checkout
              uses: actions/checkout@v3

            - uses: actions-ecosystem/action-regex-match@v2
              id: regex-match
              with:
                text: ${{ github.ref_name }}
                regex: '^v\d+.\d+.\d+(-dev\d+|.\w+)'

            - run: echo ${{ steps.regex-match.outputs }}

            - name: RegRes
              if: ${{ steps.regex-match.outputs.match != '' }}
              run: echo ${{ steps.regex-match.outputs.match }}


